apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-micro-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-micro
  template:
    metadata:
      labels:
        app: go-micro
    spec:
      containers:
        - name: go-micro
          image: .:latest  # Using the current directory's Dockerfile
          ports:
            - containerPort: 80
