apiVersion: v1
kind: Service
metadata:
  name: go-micro-service
  namespace: dev
spec:
  selector:
    app: go-micro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer